### ISSUE TITLE
[Feature] Simulation support

### ISSUE THREAD

**Issue by AustinDeric** [microsoft/spot-ros-wrapper#18]
It should be possible to operate Spot in a simulator such as gazebo or Airsim

**Comment by amjack0** [comment]
any Updates on this?

**Comment by jeffdelmerico** [comment]
Unfortunately, even the "officially supported" wrapper from [Clearpath ](https://github.com/clearpathrobotics/spot_ros) does not have any simulation capabilities.  As far as I'm aware, Boston Dynamics is not planning to release something like that in the future.  While it may be possible to implement an approximation to the robot within Gazebo, it would not include the full dynamic model that BD has access to, or any of the perception, planning, and control algorithms that I assume are proprietary, so it's unclear how useful such a "homebrew" model would be.
