### ISSUE TITLE
How to visualize the Robot model in Rviz? 

### ISSUE THREAD

**Issue by arjunskumar** [microsoft/spot-ros-wrapper#7]
Couldn't find URDF descriptions files in the packages.

**Comment by helenol** [comment]
Hi @arjunskumar, we're currently working with BD to make sure we can include the spot URDFs in our repo. :) We'll keep you updated on when this happens.

**Comment by arjunskumar** [comment]
Thanks @helenol

**Comment by mklingen-bd** [comment]
@helenol @arjunskumar  our API provides a URDF via the `Skeleton` message within robot state. The intention was for API users to dynamically download the URDF from the robot and display it that way -- but this is probably much more difficult to achieve in ROS than a static `spot_description` package containing a copy of the URDF.

**Comment by arjunskumar** [comment]
@mklingen-bd Yes you're right.
